name: 'Changed Files action'
description: 'Detected changed files'
author: ''
inputs:
  github_token:
    required: true
    description: ''
  source:
    required: false
    description: 'The commit source'
    default: 'HEAD'
  target:
    required: false
    description: 'The commit target'
    default: 'HEAD~1'
  pattern:
    required: false
    description: 'Gloob pattern to filter files'
    default: '**'
outputs:
  has-changes:
    description: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
