name: 'Changed Files action'
description: 'Detected changed files'
author: ''
inputs:
  github_token:
    required: true
    description: ''
  source:
    required: false
    description: ''
  target:
    required: false
    description: ''
  pattern:
    required: false
    description: ''
outputs:
  has-changes:
    description: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
